from pathlib import Path

path = Path("tools/patch_instant_layer_handoffs.py")
text = path.read_text()
old = '''block_call = \'\'\'        blockWebsite(\n            browserPackageName = packageName,\n            browserWindowId = event.windowId,\n            blockedCandidate = url ?: addressText ?: blockedCandidate,\n            detectionEventUptimeMillis = event.eventTime\n        )\n\'\'\'\nroute_call = \'\'\'        routeWebsiteBlockByHierarchy(\n            browserPackageName = packageName,\n            browserWindowId = event.windowId,\n            blockedCandidate = url ?: addressText ?: blockedCandidate,\n            detectionEventUptimeMillis = event.eventTime\n        )\n\'\'\'\nreplace_count(service, block_call, route_call, 2)\n'''
new = '''immediate_block_call = \'\'\'        blockWebsite(\n            browserPackageName = packageName,\n            browserWindowId = event.windowId,\n            blockedCandidate = url ?: addressText ?: blockedCandidate,\n            detectionEventUptimeMillis = event.eventTime\n        )\n\'\'\'\nimmediate_route_call = \'\'\'        routeWebsiteBlockByHierarchy(\n            browserPackageName = packageName,\n            browserWindowId = event.windowId,\n            blockedCandidate = url ?: addressText ?: blockedCandidate,\n            detectionEventUptimeMillis = event.eventTime\n        )\n\'\'\'\nreplace_once(service, immediate_block_call, immediate_route_call)\n\nroot_block_call = \'\'\'            blockWebsite(\n                browserPackageName = packageName,\n                browserWindowId = event.windowId,\n                blockedCandidate = url ?: addressText ?: blockedCandidate,\n                detectionEventUptimeMillis = event.eventTime\n            )\n\'\'\'\nroot_route_call = \'\'\'            routeWebsiteBlockByHierarchy(\n                browserPackageName = packageName,\n                browserWindowId = event.windowId,\n                blockedCandidate = url ?: addressText ?: blockedCandidate,\n                detectionEventUptimeMillis = event.eventTime\n            )\n\'\'\'\nreplace_once(service, root_block_call, root_route_call)\n'''
if text.count(old) != 1:
    raise SystemExit(f"expected patch stanza once, found {text.count(old)}")
path.write_text(text.replace(old, new, 1))
